### ISSUE TITLE
Fortran runtime error

### ISSUE THREAD

**Issue by xinglong-zhang** [materialsvirtuallab/maml#252]
Hi, while running the pes/gap example, i encountered the following error:

> INFO:maml.utils._lammps:Structure index 0 is rotated.
INFO:maml.utils._lammps:Structure index 1 is rotated.
INFO:maml.utils._lammps:Structure index 2 is rotated.
INFO:maml.utils._lammps:Structure index 3 is rotated.
INFO:maml.utils._lammps:Structure index 4 is rotated.
INFO:maml.utils._lammps:Structure index 5 is rotated.
INFO:maml.utils._lammps:Structure index 6 is rotated.
INFO:maml.utils._lammps:Structure index 7 is rotated.
INFO:maml.utils._lammps:Structure index 8 is rotated.
INFO:maml.utils._lammps:Structure index 9 is rotated.
Fortran runtime error: Incorrect extent in VALUE argument to DATE_AND_TIME intrinsic: is -2, should be >=8

Error termination. Backtrace:
#0  0x5599f40f562a in ???
#1  0x5599f3cf11ea in ???
#2  0x5599f3cf0cae in ???
#3  0x7fd4f1abc0b2 in ???
#4  0x5599f3cf0ced in ???
#5  0xffffffffffffffff in ???
Traceback (most recent call last):
  File "/home/xinglong/anaconda3/envs/ml/lib/python3.8/site-packages/maml/apps/pes/_gap.py", line 343, in train
    error_line = [i for i, m in enumerate(msg) if m.startswith("ERROR")][0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 17, in <module>
    gap.train(train_structures=train_structures, train_energies=train_energies,
  File "/home/xinglong/anaconda3/envs/ml/lib/python3.8/site-packages/maml/apps/pes/_gap.py", line 346, in train
    error_msg += msg[-1]
IndexError: list index out of range

From the limited answers online, it seems that this suggests that the gfortran used to compile the program (QUIP/gap_fit) is different from the one that is used during the run. However, the gfortran i have on the machine is the same one used for compiling and running. The detail architech of the machine is linux_x86_64, the gfortran version is `GNU Fortran (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0` and the gcc version is `gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0`.

This may be due to the gap_fit program of QUIP, wondering if you are able to advise on possible solutions please?

Thank you for your kind attention.

**Comment by xinglong-zhang** [comment]
This has been shown to be an error in my compilation of QUIP, this has been solved by successfully compiling the QUIP program. Please kindly close the issue, thank you.
