### ISSUE TITLE
A code running error

### ISSUE THREAD

**Issue by loilisxka** [materialsvirtuallab/maml#473]
Hi, we are trying to generate BispectrumCoefficients descriptors using the maml package, but we are experiencing some code problems that we hope you can answer.
When running the site_describer.ipynb file in the Jupyter notebooks example file you gave, the python terminal shows in
bc = BispectrumCoefficients(rcutfac=0.5, twojmax=2,
             element_profile={'Mo': {'r': '8', 'w': '1'}}) in
It encounters a problem and does not work. The specific error is reported as:

D:\programingTool\anaconda\envs\torch1\lib\site-packages\maml\apps\pes\_lammps.py:38: FutureWarning: which is deprecated; use which in shutil instead.
shutil.which has been available since Python 3.3. This will be removed in v2023.
  if which(lmp_exe) is not None:
D:\programingTool\anaconda\envs\torch1\lib\site-packages\maml\apps\pes\_lammps.py:85: FutureWarning: which is deprecated; use which in shutil instead.
shutil.which has been available since Python 3.3. This will be removed in v2023.
  if not which(lmp_exe):
Traceback (most recent call last):
  File "D:\programingTool\anaconda\envs\torch1\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "D:\programingTool\PyCharm Community Edition 2021.3.3\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\programingTool\PyCharm Community Edition 2021.3.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/code/py/pytorch/describe/SNAP.py", line 7, in <module>
    element_profile={'Mo': {'r': '8', 'w': '1'}})
  File "D:\programingTool\anaconda\envs\torch1\lib\site-packages\maml\describers\_site.py", line 83, in __init__
    rcutfac=rcutfac, twojmax=twojmax, element_profile=element_profile, quadratic=quadratic
  File "D:\programingTool\anaconda\envs\torch1\lib\site-packages\maml\apps\pes\_lammps.py", line 306, in __init__
    super().__init__(**kwargs)
  File "D:\programingTool\anaconda\envs\torch1\lib\site-packages\maml\apps\pes\_lammps.py", line 85, in __init__
    if not which(lmp_exe):
  File "D:\programingTool\anaconda\envs\torch1\lib\site-packages\monty\dev.py", line 51, in wrapped
    return old(*args, **kwargs)
  File "D:\programingTool\anaconda\envs\torch1\lib\site-packages\monty\os\path.py", line 31, in which
    fpath, fname = os.path.split(cmd)
  File "D:\programingTool\anaconda\envs\torch1\lib\ntpath.py", line 183, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

The same problem occurs in linux server, please tell me why? I'm looking forward to your reply, thanks!

**Comment by JiQi535** [comment]
@loilisxka Hi! Would you please confirm if the LAMMPS executables are already put into your $PATH, so that it can be found by the `which` function in the `shutil` package?  To check this, you can run below scripts in your notebook:
```
from shutil import which
which("lmp_mpi") #in case your LAMMPS exe has a name of "lmp_mpi"
```
The above script should give a correct path to your lmp executable. Does the error exist if the `which` function can return a correct path to the exectuable?
